config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :books
    # end
    root to: 'users#index'
  end
  get 'static_pages/about'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, except: [:index], shallow: true do
    resources :finished_books, only: [:index]
    resources :books, defaults: { format: 'html' }, except: [:show] do
      member do
        get 'really_destroy'
        patch 'restore'
      end
    end
  end

  resource :user_sessions, only: [:create, :new, :destroy]
  # [POST] "/user_sessions/new"
  resources :password_resets, only: [:create, :edit, :update]
  # get :login, to: 'user_sessions#new'
  # delete :logout, to: 'user_sessions#destroy'
  # resources :user_sessions, only: %i[create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # http://c5meru.hatenablog.jp/entry/2018/07/29/200011
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'user_sessions#new'
end

app/models/book.rb
class Book < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  default_scope -> { order(:user_id, :priority) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 129 }
  # ロビンソン・クルーソーが129文字
  validate :when_stop_should_be_after_when_start

  def still_not_read?
    # 未読。読書中でもなく、かつ既読でもない
    # 完全な未読と中断を区別していない。yagni
    !reading? && !had_read?
  end

  def reading?
    when_start && !when_stop && !deleted_at
  end

  def had_read?
    # ただのシンタックスシュガー。二重否定でboolに変える
    !!deleted_at
  end

  private

  def when_stop_should_be_after_when_start
    return unless when_stop && when_start

    errors.add(:when_stop, 'は開始日より前には設定できません') if when_stop < when_start
  end
end

app/controllers/admin/books_controller.rb
module Admin
  class BooksController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_book_owner, except: %i[index new create]
  before_action :correct_user, only: %i[index new create]

  def index
    # @user = User.find(params[:user_id])
    @q = @user.books.ransack(params[:q])
    @books = @q.result # (distinct: true)は複数の検索結果をまとめる
  end

  def edit
    @book = Book.with_deleted.find(params[:id])
  end

  def update
    @book = Book.with_deleted.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to current_user, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    # @user = User.find(params[:user_id])
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to current_user, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: current_user }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def really_destroy
    @book = Book.with_deleted.find(params[:id])
    @book.really_destroy!
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Book was successfully really destroyed.' }
      format.json { head :no_content }
    end
  end

  def restore
    @book = Book.only_deleted.find(params[:id])
    @book.restore
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Book was successfully restored.' }
      format.json { head :no_content }
    end
  end
  # Override this method to specify custom lookup behavior.
  # This will be used to set the resource for the `show`, `edit`, and `update`
  # actions.
  #
  # def find_resource(param)
  #   Foo.find_by!(slug: param)
  # end

  # The result of this lookup will be available as `requested_resource`

  # Override this if you have certain roles that require a subset
  # this will be used to set the records shown on the `index` action.
  #
  # def scoped_resource
  #   if current_user.super_admin?
  #     resource_class
  #   else
  #     resource_class.with_less_stuff
  #   end
  # end

  # Override `resource_params` if you want to transform the submitted
  # data before it's persisted. For example, the following would turn all
  # empty values into nil values. It uses other APIs such as `resource_class`
  # and `dashboard`:
  #
  # def resource_params
  #   params.require(resource_class.model_name.param_key).
  #     permit(dashboard.permitted_attributes).
  #     transform_values { |value| value == "" ? nil : value }
  # end

  # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
  # for more information
  private

  def book_params
    params.require(:book).permit(:title, :priority, :when_start, :when_stop, :deleted_at).merge(user_id: current_user.id)
  end

  def correct_user
    @user = User.find(params[:user_id])
    redirect_to(root_url) unless @user == current_user
  end

  def correct_book_owner
    redirect_to(root_url) unless Book.with_deleted.find(params[:id]).user_id == current_user.id
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr id="book-<%= book.id %>">
  <%= tag.td link_to  book.title, edit_book_path(book) %>
  <%= tag.td jpn_priority(book.priority) %>
  <%= tag.td book.when_start %>
  <%= tag.td book.when_stop %>
<!--開始ボタンと再開ボタンは共通。内部でif分岐-->
  <td>
    <% if book.still_not_read? %>
      <% when_start = book.when_start || Date.today %>
      <%= button_to '開始', book_path(book), {method: :patch, params: {book:{when_start: when_start, when_stop: nil} } } %>
    <% elsif book.reading? %>
      <%= button_to '読了',book_path(book), method: :delete %>
    <% elsif book.had_read? %>
      <%= button_to '完全削除', really_destroy_book_path(book), method: :get, data: { confirm: '削除した本は復旧できません。よろしいですか?' } %>
    <% end %>
  </td>

  <!--<td>%= link_to '削除', book, method: :delete, data: { confirm: '削除した本は復旧できません。よろしいですか?' } %></td>-->
</tr>

app/views/books/_form.html.erb
<%= form_with(model:[@user, @book]) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
  　<%= form.label :priority %>
  　<%= form.select :priority, list_priorities, prompt: "優先度を選択してください"  %>
  </div>

  <div class="actions my-button">
    <%= form.submit "書籍情報を保存する", class: "btn btn-block" %>
  </div>
<% end %>

app/views/books/_table_header.html.erb
<tr>
  <%= tag.th "題名" %>
  <%= tag.th "優先度" %>
  <%= tag.th "開始日" %>
  <%= tag.th "中断日" %>
  <th></th>
</tr>

app/views/books/edit.html.erb
<h1>書籍の情報を編集する</h1>

<!--別の人の本を指定したときの警告がない。いつか追加する-->

<%= render 'form', book: @book %>

<!--読書開始ボタン。入力済だったら上書きしない。中断日フィールドを消す-->
<% when_start = @book.when_start || Date.today %>
<%= button_to '開始', book_path(@book), {method: :patch, params: {book:{when_start: when_start, when_stop: nil} }, disabled: !@book.still_not_read? } %>
<!--読了ボタン-->
<%= button_to '読了',book_path(@book), {method: :delete, disabled: !@book.reading? } %>
<!--中断ボタン。中断日は問答無用で今日でいい-->
<%= button_to '中断',book_path(@book), {method: :patch, params: {book:{when_stop: Date.today} }, disabled: !@book.reading? } %>
<!--削除ボタン-->
<%= button_to '完全削除', really_destroy_book_path(@book), method: :get, data: { confirm: '削除した本は復旧できません。よろしいですか?' } %>
<!--復旧ボタン-->
<%= button_to '復旧', restore_book_path(@book), {method: :patch,disabled: !@book.had_read? } %>

<%= link_to 'キャンセル', :back %>

app/views/books/index.html.erb
<h1>
  <%= "こんにちは、#{@user.user_name}さん" %>
</h1>

<p>
  <% if @user.email.nil? then %>
    メールアドレスが未登録です。
  <% else %>
    <strong>メールアドレス:</strong>
    <%= @user.email %>
  <% end %>
</p>

<!--管理者のときだけ管理者画面リンクを出す-->
<% if @user.admin? %>
  <%= link_to "管理者画面", admin_root_path %> |
<% end %>

<% if @books&.only_deleted&.any? %>
  <%= link_to "読了済みリストを見る", user_finished_books_path(@user) %> |
<% end %>


<!--crypted passwordとsaltは削除-->
<%= link_to 'ユーザー情報を編集する', edit_user_path(@user) %> |
<%= link_to '新しく本を登録する', new_user_book_path(user_id: @user.id) %> |
<%= link_to "ログアウトする", logout_path, method: :post %>

<%= search_form_for @q, url: user_books_path(@user) do |f| %>
  <%= f.label :title_cont, "本を検索する" %>
  <%= f.search_field :title_cont %> |
  <%= f.submit "検索実行",class: 'btn-white' %>
<% end %>

 <div class="col-md-8">
    <%= tag.h3 "登録された本は#{@books.count}冊です。" %>
    <% if @books&.any?(&:reading?) %>
      <%= tag.h4 "読書中リスト" %>
      <table class="reading_book">
        <thead>
          <%= render partial: "books/table_header" %>
        </thead>
        <tbody>
          <%= render @books.filter(&:reading?) %>
        </tbody>
      </table>
    <% else %>
      現在読書中の本はありません。
    <% end %>

    <% if @books&.any?(&:still_not_read?) %>
      <%= tag.h4 "未読リスト" %>
      <table class="will_read_books zebra">
        <thead>
          <%= render partial: "books/table_header" %>
        </thead>
        <tbody>
          <%= render @books.filter(&:still_not_read?) %>
        </tbody>
      </table>

    <% else %>
      <%= link_to 'ここをクリックして、本を登録しましょう！', new_user_book_path(user_id: @user.id) %>
    <% end %>
</div>

app/views/books/new.html.erb
<h1>新しい本を追加する</h1>

<%= render 'form', book: @book %>

<%= link_to 'キャンセル', :back %>