config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :books
    # end
    root to: 'users#index'
  end
  get 'static_pages/about'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, except: [:index], shallow: true do
    resources :finished_books, only: [:index]
    resources :books, defaults: { format: 'html' }, except: [:show] do
      member do
        get 'really_destroy'
        patch 'restore'
      end
    end
  end

  resource :user_sessions, only: [:create, :new, :destroy]
  # [POST] "/user_sessions/new"
  resources :password_resets, only: [:create, :edit, :update]
  # get :login, to: 'user_sessions#new'
  # delete :logout, to: 'user_sessions#destroy'
  # resources :user_sessions, only: %i[create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # http://c5meru.hatenablog.jp/entry/2018/07/29/200011
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'user_sessions#new'
end

app/controllers/user_sessions_controller.rb
# app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:user_name], params[:password])
    if @user
      redirect_back_or_to(user_books_path(@user), notice: 'ログインしました。')
      # 昔はredirect_back_or_to(@user, notice: 'Login successfull.')だったが、ユーザーのインデックスページはなくした
    else
      flash.now[:alert] = 'ログインに失敗しました。'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_url, notice: 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_with url: password_resets_path, local: true, method: :post do |form| %>
  <div class="field">
    <%= form.label :email %><br />
    <%= form.text_field :email %>
    <%= form.submit "パスワードリセット" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_with url: user_sessions_path, method: :post, local: true do |f| %>
  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<!--require "action_view"-->
<!--include ActionView::Helpers::TagHelper-->
<!--singleton_class.class_eval { attr_accessor :output_buffer }-->


<%= tag.h1 "ログイン" %>
<div class="f-row-container">
    <div class="f-column-container">
        <%= tag.h2 "アカウントをお持ちのユーザーはこちら" %>
        <%= render 'form' %>
        <%= tag.h3 "パスワードを忘れた人は" %>
        <%= render 'forgot_password_form' %>
        <%= link_to "letter_opener", letter_opener_web_path if Rails.env.development? %>
    </div>
    <div class="f-column-container">
        <%= tag.h2 "新規のユーザーはこちら" %>
        <!--Launch demo modal-->
        <div class="my-button">
            <%= button_to "アカウント作成", new_user_path,{method: :get, class: "btn btn-block" } %>
        </div>
        <div class="my-button">
            <%= button_to "FAQページ", static_pages_about_path,{method: :get, class: "btn btn-block" } %>
        </div>
        <div class="my-button">
        <%= button_to "ゲストユーザーとしてログイン",
                        user_sessions_path,
                        {method: :post, params: { user_name: 'Example User', password: 'foobar' }, class: "btn btn-block" } %>
        </div>
    </div>
</div>